# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.7'
# Define services
services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: registration # Use an image built from the specified dockerfile in the `registration` directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on: 
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/regs_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: registration_u
      SPRING_DATASOURCE_PASSWORD: registration_p
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
  # Database Service (Mysql)
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: regs_db
      MYSQL_USER: registration_u
      MYSQL_PASSWORD: registration_p
      MYSQL_ROOT_PASSWORD: root0808
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
# Volumes
volumes:
  db-data:
# Networks to be created to facilitate communication between containers
networks:
  backend: